name = "GenieLicensing"
uuid = "053420ac-561e-47bc-88a1-f3908d4a7fc1"
authors = ["Adrian Salceanu <adrian.salceanu@gmail.com> and contributors"]
version = "1.0.1-DEV"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[compat]
HTTP = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
